### ISSUE TITLE
DBCursor class is no more with latest mongojack or after 2.10.1

### ISSUE THREAD

**Issue by kssahoo** [mongojack/mongojack#217]
Since DBCursor is no more available in 4.2.0 or after 2.10.1, what is the alternative for the class?

**Comment by rlodge** [comment]
There is an incomplete migration guide at https://github.com/mongojack/mongojack/blob/master/MIGRATING.md.  The key is essentially that a JacksonMongoCollection _is_ a MongoCollection, so you can use all functionality that class provides, as documented in the standard MongoDB java driver documentation.  Instead of DBCursor, you the collection returns a FindIterable, for instance.

If you have a more specific question, I might be able to help further.

**Comment by kssahoo** [comment]
@rlodge, This is helpful! Thanks!
