### ISSUE TITLE
$in query serialization broken

### ISSUE THREAD

**Issue by benmccann** [mongojack/mongojack#88]
As reported in https://github.com/devbliss/mongojack/pull/46 and https://github.com/devbliss/mongojack/issues/27, [$in queries](http://docs.mongodb.org/manual/reference/operator/query/in/) are not being serialized correctly

I've checked in a test case that fails:
https://github.com/devbliss/mongojack/commit/b9375425a7ac538daaecb3aeafb31450c37c6784

I believe the problem is either that a `StringCollectionSerializer` is being used to serialize each individual `String` in the collection instead of serializing the whole collection at once
https://github.com/jroper/mongojack/blob/master/src/main/java/org/mongojack/internal/util/SerializationUtils.java#L185

**Comment by benmccann** [comment]
@jroper do you know if we should be using a CompoundQueryCondition or a CollectionQueryCondition when serializing this query condition? https://github.com/devbliss/mongojack/commit/b9375425a7ac538daaecb3aeafb31450c37c6784

**Comment by benmccann** [comment]
@jroper if you could add a short Javadoc to those two classes I should be able to handle the rest

**Comment by benmccann** [comment]
Hmmm. CollectionQueryCondition seems much different than what I thought it was. It looks like it should have been called QueryConditionCollection instead and is used when you have multiple query conditions with an "and" or an "or". Of course I thought from the name that's what CompoundQueryCondition was, so now I have to figure out what exactly it is.

**Comment by benmccann** [comment]
Aye yai yai, I have no idea now what `collection` means in `SerializationUtils`. I thought it meant a MongoDB collection (like a DB table), but now I'm wondering if it means a collection of queries? I really don't understand what it mean.

**Comment by benmccann** [comment]
`CompoundQueryCondition` seems to just be a `QueryConditionImpl`. As far as I can tell the word compound is meaningless

**Comment by jroper** [comment]
Been a long time since I looked at this stuff, so I could be wrong...

* `CollectionQueryCondition` means neither of those, it's for query conditions that have a collection of values, such as the `in` or `notIn`.  It's important in these situations to serialise each value using the fields serialiser, not the whole collection using the fields serialiser.
* `CompoundQueryCondition` - I think this is when you have multiple query conditions on one field.
* I think `targetIsCollection` this seems to have something to do with `mod`, which takes a list of the modulo and the remainder, which is similar but in contrast to a regular collection query condition like `in` or `notIn` which just has a list of values, in that case serialising must happen a little differently, but I'm not sure how.
* `requiresSerialization` I think is for things like the `mod` operator, since it's only valid to pass an int to the `mod` operator and use as is.  It should be true for `String`, since you might have a custom Jackson serialiser on that field that transforms the string (eg, encrypts it?).

**Comment by joschi** [comment]
Is there any workaround for this issue in MongoJack 2.3.0?

**Comment by benmccann** [comment]
You can create a DBObject yourself I believe and not rely on MongoJack to do it

**Comment by joschi** [comment]
@benmccann Yes, that certainly works (it's my current workaround) but I was hoping for something I could use within MongoJack. Thanks!
